// File: RetailChainUi/src/configs/roleRoutes.config.js

export const ROLE_PERMISSIONS = {
  STAFF: ['STORE_VIEW', 'PRODUCT_VIEW', 'INVENTORY_VIEW'],
  STORE_MANAGER: [
    'STORE_VIEW',
    'PRODUCT_VIEW',
    'PRODUCT_CREATE',
    'INVENTORY_VIEW',
    'INVENTORY_UPDATE',
    'INVENTORY_TRANSFER',
    'STOCKIN_CREATE',
    'STOCKIN_VIEW',
    'STOCKOUT_CREATE',
    'STOCKOUT_VIEW',
    'HR_VIEW',
    'HR_UPDATE',
    'SHIFT_VIEW',
    'SHIFT_UPDATE',
    'USER_VIEW',
    'USER_CREATE',
    'USER_UPDATE',
    'USER_BLOCK',
    'USER_UNBLOCK',
    'REPORT_VIEW'
  ],
  SUPER_ADMIN: [
    'STORE_CREATE',
    'STORE_VIEW',
    'STORE_UPDATE',
    'STORE_DELETE',
    'PRODUCT_VIEW',
    'PRODUCT_CREATE',
    'PRODUCT_UPDATE',
    'PRODUCT_DELETE',
    'INVENTORY_VIEW',
    'INVENTORY_UPDATE',
    'INVENTORY_TRANSFER',
    'STOCKIN_CREATE',
    'STOCKIN_VIEW',
    'STOCKOUT_CREATE',
    'STOCKOUT_VIEW',
    'HR_VIEW',
    'HR_UPDATE',
    'HR_DELETE',
    'SHIFT_VIEW',
    'SHIFT_UPDATE',
    'SHIFT_DELETE',
    'USER_VIEW',
    'USER_CREATE',
    'USER_UPDATE',
    'USER_DELETE',
    'USER_BLOCK',
    'USER_UNBLOCK',
    'REPORT_VIEW',
    'ROLE_VIEW',
    'ROLE_CREATE',
    'ROLE_UPDATE',
    'ROLE_DELETE',
    'PERMISSION_VIEW',
    'WAREHOUSE_VIEW',
    'WAREHOUSE_CREATE',
    'WAREHOUSE_UPDATE',
    'WAREHOUSE_DELETE'
  ]
};

export const ROUTE_PERMISSIONS = {
  '/': [],
  '/reports': ['REPORT_VIEW'],
  '/store': ['STORE_VIEW'],
  '/store/:id': ['STORE_VIEW'],
  '/store/:id/inventory': ['STORE_VIEW'],
  '/store/:id/staff': ['HR_VIEW', 'HR_UPDATE'],
  '/warehouse': ['WAREHOUSE_VIEW'],
  '/products': ['PRODUCT_VIEW'],
  '/products/create': ['PRODUCT_CREATE'],
  '/products/:slug': ['PRODUCT_VIEW'],
  '/products/:slug/edit': ['PRODUCT_UPDATE'],
  '/inventory': ['INVENTORY_VIEW'],
  '/inventory/ledger': ['INVENTORY_VIEW'],
  '/stock-in': ['STOCKIN_VIEW'],
  '/stock-in/create': ['STOCKIN_CREATE'],
  '/stock-out': ['STOCKOUT_VIEW'],
  '/stock-out/create': ['STOCKOUT_CREATE'],
  '/staff': ['HR_VIEW'],
  '/staff/shifts': ['SHIFT_VIEW', 'SHIFT_UPDATE'],
  '/staff/calendar': ['SHIFT_VIEW'],
  '/staff/attendance': ['HR_VIEW', 'HR_UPDATE'],
  '/staff/profile/:id': ['HR_VIEW'],
  '/staff/resource': ['HR_UPDATE'],
  '/users': ['USER_VIEW'],
  '/profile': [],
  '/roles': ['ROLE_VIEW']
};
