spring.application.name=RetailChainService

server.port=8080
server.servlet.context-path=/retail-chain
# MySQL
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/retail_2
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=false
spring.web.resources.add-mappings=false
openapi.service.title=My Awesome API
openapi.service.version=1.0.0
openapi.service.url=${APP_BASE_URL:http://localhost:8080/retail-chain}

#springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha
# springdoc.swagger-ui.enabled=false

logging.level.org.springframework.core.env=DEBUG
# security config
spring.security.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970337336763979244226452948404D6351
spring.security.jwt.access-token-expiration=3600
spring.security.jwt.refresh-token-expiration=604800
spring.security.jwt.refresh-token-secret=782F413F4428472B4B6250655368566D597133743677397A24432646294A404E635266556A586E327235753877217A25432A462D4A614E645267556A586E3272
